### ISSUE TITLE
Custom front matter doesn’t get evaluated

### ISSUE THREAD

**Issue by isellsoap** [paulrobertlloyd/paulrobertlloyd-v4#2]
You have to change your usage of 

```
{% if page.data.hidden == true %}
```

in `default.liquid` to

```
{% if hidden == true %}
```

as `page.data.hidden` doesn’t seem to return anything.

**Comment by paulrobertlloyd** [comment]
Wow, great catch @isellsoap! This has now been fixed, thanks for letting me know.
