### ISSUE TITLE
Not able to run application

### ISSUE THREAD

**Issue by punampatekar123** [paulrobertlloyd/paulrobertlloyd-v4#4]
Hi Team,

I am trying to setup this application on my local machine but not able to make it up and running.
When i run cmd "npm run build" it throwing error as "Problem writing Eleventy templates"
I have already run below cmds- 
1)  npm install and 
2) npm install --save-dev @11ty/eleventy 
but still facing issue and not able to run application.
Please help. It would really help me out.

Thanks in advance,
Punam

**Comment by paulrobertlloyd** [comment]
Hi Punam. What exactly are you trying to achieve? This is my personal website, not an application.
